name: proxysql-cluster
version: 1.0.0
description: Chart for ProxySQL Cluster
keywords:
- mysql
- database
- proxysql
- cluster
home: http://www.proxysql.com/
sources:
- https://github.com/sysown/proxysql
maintainers:
- name: Jasper de Jager
  email: jasper@scienta.nl
- name: Tim Mirecki
  email: tim@carpages.ca
engine: gotpl
